name: free_games_giveaways
description: A new Flutter project.

publish_to: "none"

version: 2.8.5+6

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  animate_do: ^2.0.0
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  firebase_analytics: ^8.3.3
  firebase_core: ^1.4.0
  firebase_crashlytics: ^2.1.1
  firebase_messaging: ^10.0.4
  flutter:
    sdk: flutter
  flutter_bloc: ^7.1.0
  flutter_form_builder: ^6.0.1
  flutter_local_notifications: ^8.1.1+1
  flutter_snake_navigationbar: ^0.5.0
  flutter_svg: ^0.23.0+1
  font_awesome_flutter: ^9.1.0
  freezed_annotation: ^0.15.0
  getwidget: ^2.0.1-nullsafety.4
  google_fonts: ^2.1.0
  google_mobile_ads: ^1.2.0
  http: ^0.13.3
  json_annotation: ^4.3.0
  logger: ^1.1.0
  lottie: ^1.2.1
  octo_image: ^1.0.0+1
  rflutter_alert: ^2.0.4
  share_plus: ^2.1.4
  url_launcher: ^6.0.9

dev_dependencies:
  build_runner: ^2.1.5
  flutter_launcher_icons: ^0.9.1
  flutter_test:
    sdk: flutter
  freezed: ^0.15.1+1
  json_serializable: ^6.0.1
  lint: ^1.6.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/licenses/
    - assets/animations/
    - assets/icons/
